# Generated by Django 4.0.5 on 2022-06-16 13:36

from django.contrib.auth.hashers import make_password
from django.db import migrations

from hello_world.models import User


def insert_sample(*args):
    User.objects.create(
        username='example-user',
        first_name='example',
        last_name='user',
        email='example-user@example.com',
        password=make_password('password')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sample, reverse_code=migrations.RunPython.noop, atomic=True)
    ]
